import { HouseGamePrimitive } from '@/types/houseGame';

export const BONUS_PRIMITIVES: HouseGamePrimitive[] = [
  {
    id: 'bonus_par5_double',
    category: 'bonus',
    label: 'Par-5 holes double',
    description: 'The stake is doubled on every par-5 hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'bonus_par3_special',
    category: 'bonus',
    label: 'Par-3 special rule',
    description: 'Apply a special rule to par-3 holes: double stake, half stake, or a separate side pot.',
    valueType: 'select',
    valueConfig: { options: ['none', 'double', 'half', 'separate_pot'] },
    defaultValue: 'none',
    implemented: false,
  },
  {
    id: 'bonus_birdie_unit',
    category: 'bonus',
    label: 'Birdie unit bonus',
    description: 'Each birdie pays an additional unit bonus to the scorer from all other players.',
    valueType: 'number',
    valueConfig: { min: 0, max: 10, step: 1 },
    defaultValue: 1,
    implemented: true,
  },
  {
    id: 'bonus_eagle_unit',
    category: 'bonus',
    label: 'Eagle unit bonus',
    description: 'Each eagle (or better) pays an additional unit bonus to the scorer from all other players.',
    valueType: 'number',
    valueConfig: { min: 0, max: 20, step: 1 },
    defaultValue: 2,
    implemented: true,
  },
  {
    id: 'bonus_greenie',
    category: 'bonus',
    label: 'Greenies',
    description: 'On par-3s, the player closest to the pin in regulation and who makes par or better wins a greenie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_sandie',
    category: 'bonus',
    label: 'Sandies',
    description: 'A player who makes par (or better) after being in a bunker earns a sandie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_barkie',
    category: 'bonus',
    label: 'Barkies',
    description: 'A player who makes par (or better) after hitting a tree earns a barkie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_oozle',
    category: 'bonus',
    label: 'Oozles',
    description: 'Awarded when a player 3-putts; collected by all players who do not 3-putt on that hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_chippy',
    category: 'bonus',
    label: 'Chippies',
    description: 'A player who chips in from off the green earns a chippy bonus.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_polie',
    category: 'bonus',
    label: 'Polies (Poles)',
    description: 'The player who 2-putts from the longest distance on a hole wins a polie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_last_hole_double',
    category: 'bonus',
    label: 'Last hole doubles',
    description: 'The stake on hole 18 is doubled for all active bets.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'bonus_garbage_tracking',
    category: 'bonus',
    label: 'Garbage / junk tracking',
    description: 'Track all garbage side bets (greenies, sandies, barkies, etc.) as a combined pot.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
];
