import { HouseGamePrimitive } from '@/types/houseGame';

export const CASUAL_PRIMITIVES: HouseGamePrimitive[] = [
  {
    id: 'casual_gimme_distance',
    category: 'casual',
    label: 'Gimme distance',
    description: 'Putts within this distance from the hole are conceded automatically.',
    valueType: 'distance',
    valueConfig: { min: 1, max: 6, step: 0.5, unit: 'ft' },
    defaultValue: 2,
    implemented: true,
  },
  {
    id: 'casual_breakfast_ball',
    category: 'casual',
    label: 'Breakfast ball (first-tee mulligan)',
    description: 'Each player may replay their first tee shot once without penalty on hole 1.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_mulligans',
    category: 'casual',
    label: 'Mulligans per round',
    description: 'Each player may replay a shot this many times during the round without penalty.',
    valueType: 'number',
    valueConfig: { min: 0, max: 6, step: 1 },
    defaultValue: 1,
    implemented: true,
  },
  {
    id: 'casual_no_blood',
    category: 'casual',
    label: 'No blood',
    description: 'A player cannot lose more units than they win in any single round (floor at zero).',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_preferred_lies',
    category: 'casual',
    label: 'Preferred lies (winter rules)',
    description: 'Players may improve their lie in the fairway by moving the ball within one club length.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_concede_match',
    category: 'casual',
    label: 'Concede match',
    description: 'Allow a player to concede the match at any point, ending it early.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_foot_wedge',
    category: 'casual',
    label: 'Foot wedge',
    description: 'Jokingly track (or penalize) use of the "foot wedge" for a casual game.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
];
