import { HouseGamePrimitive } from '@/types/houseGame';

export const HANDICAP_PRIMITIVES: HouseGamePrimitive[] = [
  {
    id: 'handicap_full',
    category: 'handicap',
    label: 'Full handicap (100%)',
    description: 'Apply 100% of each player\'s course handicap.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_90_pct',
    category: 'handicap',
    label: '90% handicap',
    description: 'Apply 90% of each player\'s course handicap (rounded to nearest whole number).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_80_pct',
    category: 'handicap',
    label: '80% handicap',
    description: 'Apply 80% of each player\'s course handicap (rounded to nearest whole number).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_75_pct',
    category: 'handicap',
    label: '75% handicap',
    description: 'Apply 75% of each player\'s course handicap (rounded to nearest whole number).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_scratch',
    category: 'handicap',
    label: 'Scratch (no handicaps)',
    description: 'Play completely scratch — no handicap strokes applied to any player.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_stroke_index',
    category: 'handicap',
    label: 'Stroke index allocation',
    description: 'Handicap strokes are allocated by hole stroke index (difficulty ranking) rather than spread evenly.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_ghost_player',
    category: 'handicap',
    label: 'Ghost player (absent member)',
    description: 'Include a ghost player using their handicap average when a group member cannot play.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'handicap_max_cap',
    category: 'handicap',
    label: 'Handicap max cap',
    description: 'Cap the maximum handicap strokes given to any single player.',
    valueType: 'number',
    valueConfig: { min: 1, max: 36, step: 1 },
    defaultValue: 18,
    implemented: false,
  },
  {
    id: 'handicap_bump_and_run',
    category: 'handicap',
    label: 'Bump and run (low-ball handicap)',
    description: 'Subtract the lowest handicap from all players so the scratch player gets zero strokes.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'handicap_mixed_tees',
    category: 'handicap',
    label: 'Mixed tees adjustment',
    description: 'Apply course rating and slope adjustments when players play from different tees.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
];
