import { HouseGamePrimitive } from '@/types/houseGame';

export const PRESS_PRIMITIVES: HouseGamePrimitive[] = [
  {
    id: 'press_auto_x_down',
    category: 'press',
    label: 'Auto-press when X down',
    description: 'A new press starts automatically when a player is X holes down in the match.',
    valueType: 'number',
    valueConfig: { min: 1, max: 5, step: 1 },
    defaultValue: 2,
    implemented: true,
  },
  {
    id: 'press_auto_birdie',
    category: 'press',
    label: 'Auto-press on birdie',
    description: 'A new press is triggered automatically whenever any player makes a birdie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_auto_eagle',
    category: 'press',
    label: 'Auto-press on eagle',
    description: 'A new press is triggered automatically whenever any player makes an eagle or better.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_manual_request',
    category: 'press',
    label: 'Manual press request',
    description: 'Players can request a press at any time during the round.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_requires_acceptance',
    category: 'press',
    label: 'Press requires acceptance',
    description: 'The opposing side must accept a press request before it takes effect.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_double_or_nothing',
    category: 'press',
    label: 'Double or nothing press',
    description: 'A press doubles the current bet rather than starting a new parallel side bet.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_max_per_round',
    category: 'press',
    label: 'Max presses per round',
    description: 'Limit the total number of presses that can be called during a single round.',
    valueType: 'number',
    valueConfig: { min: 1, max: 10, step: 1 },
    defaultValue: 3,
    implemented: false,
  },
  {
    id: 'press_new_submatch',
    category: 'press',
    label: 'Press creates new sub-match',
    description: 'Each press starts its own independent sub-match played to the end of the round.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_no_dormie',
    category: 'press',
    label: 'No dormie press',
    description: 'A press cannot be called once either side is dormie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_back9_auto',
    category: 'press',
    label: 'Auto-press on back 9',
    description: 'A press is automatically started for all bets at the beginning of the back nine.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
];
