import { HouseGamePrimitive } from '@/types/houseGame';

// NOTE: This section preserves the original PRIMITIVES array ordering — `group_sixes`
// lives at the end of the scoring block but carries category: 'group'. Moving it
// into the group file would change the insertion order of PRIMITIVES_BY_CATEGORY's
// 'group' bucket. Keep it here to avoid behavior changes.
export const SCORING_PRIMITIVES: HouseGamePrimitive[] = [
  {
    id: 'format_nassau',
    category: 'scoring',
    label: 'Nassau',
    description: 'Three-part bet: front nine, back nine, and overall 18-hole match.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_skins',
    category: 'scoring',
    label: 'Skins',
    description: 'Each hole is worth one skin; ties carry over to the next hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_skins_back9_only',
    category: 'scoring',
    label: 'Skins – back nine only',
    description: 'Skins game is played only on the back nine holes (10–18).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_match_play',
    category: 'scoring',
    label: 'Match play',
    description: 'Hole-by-hole competition; win the hole, win a point. Most holes won wins the match.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_stroke_play',
    category: 'scoring',
    label: 'Stroke play',
    description: 'Total strokes for the round determine the winner.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_stableford',
    category: 'scoring',
    label: 'Stableford',
    description: 'Points awarded per hole based on score relative to par; highest total wins.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_modified_stableford',
    category: 'scoring',
    label: 'Modified Stableford',
    description: 'Variation of Stableford with different point values (e.g., eagle = 8, birdie = 2).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_wolf',
    category: 'scoring',
    label: 'Wolf',
    description: 'Rotating wolf selects partners hole by hole; lone wolf plays all three opponents.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_vegas',
    category: 'scoring',
    label: 'Vegas',
    description: 'Team scores are combined into a two-digit number; lower combined number wins the hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_hammer',
    category: 'scoring',
    label: 'Hammer',
    description: 'Players can double the hole stake mid-hole by calling "Hammer" before the next shot.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_bingo_bango_bongo',
    category: 'scoring',
    label: 'Bingo Bango Bongo',
    description: 'Three points per hole: first on green, closest to pin when all are on, first to hole out.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_rabbit',
    category: 'scoring',
    label: 'Rabbit',
    description: 'Win a hole outright to "catch the rabbit"; keep it until someone else wins a hole outright.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_quota',
    category: 'scoring',
    label: 'Quota',
    description: 'Each player has a quota based on handicap; points earned above quota determine the winner.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_nines',
    category: 'scoring',
    label: 'Nines (5-3-1)',
    description: 'Three-player game: 9 points per hole distributed by score rank (5/3/1, ties split).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_defender',
    category: 'scoring',
    label: 'Defender',
    description: 'One player defends against the field each hole; role rotates every hole among 3-4 players.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'group_sixes',
    category: 'group',
    label: 'Sixes (Round Robin)',
    description: 'Three six-hole matches with rotating partners; each six-hole block is a separate bet.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
];
