import { HouseGamePrimitive } from '@/types/houseGame';

export const SETTLEMENT_PRIMITIVES: HouseGamePrimitive[] = [
  {
    id: 'settlement_unit_value',
    category: 'settlement',
    label: 'Unit value ($)',
    description: 'The dollar value of one unit used throughout the round.',
    valueType: 'currency',
    valueConfig: { min: 0.25, max: 100, step: 0.25, unit: '$' },
    defaultValue: 1,
    implemented: true,
  },
  {
    id: 'settlement_pay_per_hole',
    category: 'settlement',
    label: 'Pay per hole',
    description: 'Settle winnings after each hole is completed rather than at the end of the round.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_end_of_round',
    category: 'settlement',
    label: 'Settle at end of round',
    description: 'All bets are settled in a single transaction at the conclusion of hole 18.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_running_tab',
    category: 'settlement',
    label: 'Running tab',
    description: 'Track a running balance across multiple rounds; settle whenever the group decides.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_net_out',
    category: 'settlement',
    label: 'Net out (peer-to-peer)',
    description: 'Calculate net amounts owed between every pair of players to minimize transactions.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'settlement_rain_shortened',
    category: 'settlement',
    label: 'Rain-shortened round',
    description: 'Pro-rate bets based on holes completed if the round is shortened by weather.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'settlement_max_loss_cap',
    category: 'settlement',
    label: 'Max loss cap',
    description: 'Cap the maximum dollar amount any single player can lose in one round.',
    valueType: 'currency',
    valueConfig: { min: 1, max: 500, step: 1, unit: '$' },
    defaultValue: 50,
    implemented: true,
  },
  {
    id: 'settlement_ties_split',
    category: 'settlement',
    label: 'Ties split the pot',
    description: 'When a hole or match is tied, the pot is split equally among the tied players.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_ties_carryover',
    category: 'settlement',
    label: 'Ties carry over',
    description: 'When a hole or match is tied, the pot carries over to the next hole or match.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
];
