import { HouseGamePrimitive, PrimitiveCategory } from '@/types/houseGame';

export const PRIMITIVES: HouseGamePrimitive[] = [
  // ─── PRESS RULES ────────────────────────────────────────────────────────────
  {
    id: 'press_auto_x_down',
    category: 'press',
    label: 'Auto-press when X down',
    description: 'A new press starts automatically when a player is X holes down in the match.',
    valueType: 'number',
    valueConfig: { min: 1, max: 5, step: 1 },
    defaultValue: 2,
    implemented: true,
  },
  {
    id: 'press_auto_birdie',
    category: 'press',
    label: 'Auto-press on birdie',
    description: 'A new press is triggered automatically whenever any player makes a birdie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_auto_eagle',
    category: 'press',
    label: 'Auto-press on eagle',
    description: 'A new press is triggered automatically whenever any player makes an eagle or better.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_manual_request',
    category: 'press',
    label: 'Manual press request',
    description: 'Players can request a press at any time during the round.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_requires_acceptance',
    category: 'press',
    label: 'Press requires acceptance',
    description: 'The opposing side must accept a press request before it takes effect.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_double_or_nothing',
    category: 'press',
    label: 'Double or nothing press',
    description: 'A press doubles the current bet rather than starting a new parallel side bet.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_max_per_round',
    category: 'press',
    label: 'Max presses per round',
    description: 'Limit the total number of presses that can be called during a single round.',
    valueType: 'number',
    valueConfig: { min: 1, max: 10, step: 1 },
    defaultValue: 3,
    implemented: false,
  },
  {
    id: 'press_new_submatch',
    category: 'press',
    label: 'Press creates new sub-match',
    description: 'Each press starts its own independent sub-match played to the end of the round.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_no_dormie',
    category: 'press',
    label: 'No dormie press',
    description: 'A press cannot be called once either side is dormie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'press_back9_auto',
    category: 'press',
    label: 'Auto-press on back 9',
    description: 'A press is automatically started for all bets at the beginning of the back nine.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── SCORING STRUCTURE ──────────────────────────────────────────────────────
  {
    id: 'format_nassau',
    category: 'scoring',
    label: 'Nassau',
    description: 'Three-part bet: front nine, back nine, and overall 18-hole match.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_skins',
    category: 'scoring',
    label: 'Skins',
    description: 'Each hole is worth one skin; ties carry over to the next hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_skins_back9_only',
    category: 'scoring',
    label: 'Skins – back nine only',
    description: 'Skins game is played only on the back nine holes (10–18).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'format_match_play',
    category: 'scoring',
    label: 'Match play',
    description: 'Hole-by-hole competition; win the hole, win a point. Most holes won wins the match.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_stroke_play',
    category: 'scoring',
    label: 'Stroke play',
    description: 'Total strokes for the round determine the winner.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_stableford',
    category: 'scoring',
    label: 'Stableford',
    description: 'Points awarded per hole based on score relative to par; highest total wins.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_modified_stableford',
    category: 'scoring',
    label: 'Modified Stableford',
    description: 'Variation of Stableford with different point values (e.g., eagle = 8, birdie = 2).',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_wolf',
    category: 'scoring',
    label: 'Wolf',
    description: 'Rotating wolf selects partners hole by hole; lone wolf plays all three opponents.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_vegas',
    category: 'scoring',
    label: 'Vegas',
    description: 'Team scores are combined into a two-digit number; lower combined number wins the hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_hammer',
    category: 'scoring',
    label: 'Hammer',
    description: 'Players can double the hole stake mid-hole by calling "Hammer" before the next shot.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_bingo_bango_bongo',
    category: 'scoring',
    label: 'Bingo Bango Bongo',
    description: 'Three points per hole: first on green, closest to pin when all are on, first to hole out.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_rabbit',
    category: 'scoring',
    label: 'Rabbit',
    description: 'Win a hole outright to "catch the rabbit"; keep it until someone else wins a hole outright.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_quota',
    category: 'scoring',
    label: 'Quota',
    description: 'Each player has a quota based on handicap; points earned above quota determine the winner.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_defender',
    category: 'scoring',
    label: 'Defender',
    description: 'One player defends against the field each hole; role rotates when defender loses a hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'format_sixes',
    category: 'scoring',
    label: 'Sixes (Round Robin)',
    description: 'Three six-hole matches with rotating partners; each six-hole block is a separate bet.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── MULTIPLIERS & BONUSES ───────────────────────────────────────────────────
  {
    id: 'bonus_par5_double',
    category: 'bonus',
    label: 'Par-5 holes double',
    description: 'The stake is doubled on every par-5 hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'bonus_par3_special',
    category: 'bonus',
    label: 'Par-3 special rule',
    description: 'Apply a special rule to par-3 holes: double stake, half stake, or a separate side pot.',
    valueType: 'select',
    valueConfig: { options: ['none', 'double', 'half', 'separate_pot'] },
    defaultValue: 'none',
    implemented: false,
  },
  {
    id: 'bonus_birdie_unit',
    category: 'bonus',
    label: 'Birdie unit bonus',
    description: 'Each birdie pays an additional unit bonus to the scorer from all other players.',
    valueType: 'number',
    valueConfig: { min: 0, max: 10, step: 1 },
    defaultValue: 1,
    implemented: true,
  },
  {
    id: 'bonus_eagle_unit',
    category: 'bonus',
    label: 'Eagle unit bonus',
    description: 'Each eagle (or better) pays an additional unit bonus to the scorer from all other players.',
    valueType: 'number',
    valueConfig: { min: 0, max: 20, step: 1 },
    defaultValue: 2,
    implemented: true,
  },
  {
    id: 'bonus_greenie',
    category: 'bonus',
    label: 'Greenies',
    description: 'On par-3s, the player closest to the pin in regulation and who makes par or better wins a greenie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_sandie',
    category: 'bonus',
    label: 'Sandies',
    description: 'A player who makes par (or better) after being in a bunker earns a sandie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_barkie',
    category: 'bonus',
    label: 'Barkies',
    description: 'A player who makes par (or better) after hitting a tree earns a barkie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_oozle',
    category: 'bonus',
    label: 'Oozles',
    description: 'Awarded when a player 3-putts; collected by all players who do not 3-putt on that hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_chippy',
    category: 'bonus',
    label: 'Chippies',
    description: 'A player who chips in from off the green earns a chippy bonus.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_polie',
    category: 'bonus',
    label: 'Polies (Poles)',
    description: 'The player who 2-putts from the longest distance on a hole wins a polie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_last_hole_double',
    category: 'bonus',
    label: 'Last hole doubles',
    description: 'The stake on hole 18 is doubled for all active bets.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'bonus_garbage_tracking',
    category: 'bonus',
    label: 'Garbage / junk tracking',
    description: 'Track all garbage side bets (greenies, sandies, barkies, etc.) as a combined pot.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── CARRYOVER RULES ────────────────────────────────────────────────────────
  {
    id: 'carryover_skins_halved',
    category: 'carryover',
    label: 'Skins carry on halved holes',
    description: 'When a skins hole is halved (tied), the skin carries over and adds to the next hole\'s value.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'carryover_cap',
    category: 'carryover',
    label: 'Carryover cap',
    description: 'Limit the maximum number of skins (or units) that can accumulate via carryover.',
    valueType: 'number',
    valueConfig: { min: 1, max: 18, step: 1 },
    defaultValue: 5,
    implemented: false,
  },
  {
    id: 'carryover_jackpot_18',
    category: 'carryover',
    label: 'Jackpot on hole 18',
    description: 'All unclaimed carryover skins are decided on hole 18 regardless of a tie.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'carryover_reset_on_win',
    category: 'carryover',
    label: 'Reset carryover after win',
    description: 'The carryover pot resets to zero after any player wins it.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'carryover_nassau_halved',
    category: 'carryover',
    label: 'Nassau carry on halved nine',
    description: 'If a nine-hole Nassau match is halved, the stakes carry over to the next nine.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── HANDICAP APPLICATION ───────────────────────────────────────────────────
  {
    id: 'handicap_full',
    category: 'handicap',
    label: 'Full handicap (100%)',
    description: 'Apply 100% of each player\'s course handicap.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_90_pct',
    category: 'handicap',
    label: '90% handicap',
    description: 'Apply 90% of each player\'s course handicap (rounded to nearest whole number).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_80_pct',
    category: 'handicap',
    label: '80% handicap',
    description: 'Apply 80% of each player\'s course handicap (rounded to nearest whole number).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_75_pct',
    category: 'handicap',
    label: '75% handicap',
    description: 'Apply 75% of each player\'s course handicap (rounded to nearest whole number).',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_stroke_index',
    category: 'handicap',
    label: 'Stroke index allocation',
    description: 'Handicap strokes are allocated by hole stroke index (difficulty ranking) rather than spread evenly.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'handicap_ghost_player',
    category: 'handicap',
    label: 'Ghost player (absent member)',
    description: 'Include a ghost player using their handicap average when a group member cannot play.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'handicap_max_cap',
    category: 'handicap',
    label: 'Handicap max cap',
    description: 'Cap the maximum handicap strokes given to any single player.',
    valueType: 'number',
    valueConfig: { min: 1, max: 36, step: 1 },
    defaultValue: 18,
    implemented: false,
  },
  {
    id: 'handicap_bump_and_run',
    category: 'handicap',
    label: 'Bump and run (low-ball handicap)',
    description: 'Subtract the lowest handicap from all players so the scratch player gets zero strokes.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'handicap_mixed_tees',
    category: 'handicap',
    label: 'Mixed tees adjustment',
    description: 'Apply course rating and slope adjustments when players play from different tees.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── GIMMES & CASUAL RULES ───────────────────────────────────────────────────
  {
    id: 'casual_gimme_distance',
    category: 'casual',
    label: 'Gimme distance',
    description: 'Putts within this distance from the hole are conceded automatically.',
    valueType: 'distance',
    valueConfig: { min: 1, max: 6, step: 0.5, unit: 'ft' },
    defaultValue: 2,
    implemented: true,
  },
  {
    id: 'casual_breakfast_ball',
    category: 'casual',
    label: 'Breakfast ball (first-tee mulligan)',
    description: 'Each player may replay their first tee shot once without penalty on hole 1.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_mulligans',
    category: 'casual',
    label: 'Mulligans per round',
    description: 'Each player may replay a shot this many times during the round without penalty.',
    valueType: 'number',
    valueConfig: { min: 0, max: 6, step: 1 },
    defaultValue: 1,
    implemented: true,
  },
  {
    id: 'casual_no_blood',
    category: 'casual',
    label: 'No blood',
    description: 'A player cannot lose more units than they win in any single round (floor at zero).',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_preferred_lies',
    category: 'casual',
    label: 'Preferred lies (winter rules)',
    description: 'Players may improve their lie in the fairway by moving the ball within one club length.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_concede_match',
    category: 'casual',
    label: 'Concede match',
    description: 'Allow a player to concede the match at any point, ending it early.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'casual_foot_wedge',
    category: 'casual',
    label: 'Foot wedge',
    description: 'Jokingly track (or penalize) use of the "foot wedge" for a casual game.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── SETTLEMENT ─────────────────────────────────────────────────────────────
  {
    id: 'settlement_unit_value',
    category: 'settlement',
    label: 'Unit value ($)',
    description: 'The dollar value of one unit used throughout the round.',
    valueType: 'currency',
    valueConfig: { min: 0.25, max: 100, step: 0.25, unit: '$' },
    defaultValue: 1,
    implemented: true,
  },
  {
    id: 'settlement_pay_per_hole',
    category: 'settlement',
    label: 'Pay per hole',
    description: 'Settle winnings after each hole is completed rather than at the end of the round.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_end_of_round',
    category: 'settlement',
    label: 'Settle at end of round',
    description: 'All bets are settled in a single transaction at the conclusion of hole 18.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_running_tab',
    category: 'settlement',
    label: 'Running tab',
    description: 'Track a running balance across multiple rounds; settle whenever the group decides.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_net_out',
    category: 'settlement',
    label: 'Net out (peer-to-peer)',
    description: 'Calculate net amounts owed between every pair of players to minimize transactions.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'settlement_rain_shortened',
    category: 'settlement',
    label: 'Rain-shortened round',
    description: 'Pro-rate bets based on holes completed if the round is shortened by weather.',
    valueType: 'none',
    defaultValue: null,
    implemented: true,
  },
  {
    id: 'settlement_max_loss_cap',
    category: 'settlement',
    label: 'Max loss cap',
    description: 'Cap the maximum dollar amount any single player can lose in one round.',
    valueType: 'currency',
    valueConfig: { min: 1, max: 500, step: 1, unit: '$' },
    defaultValue: 50,
    implemented: false,
  },
  {
    id: 'settlement_ties_split',
    category: 'settlement',
    label: 'Ties split the pot',
    description: 'When a hole or match is tied, the pot is split equally among the tied players.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'settlement_ties_carryover',
    category: 'settlement',
    label: 'Ties carry over',
    description: 'When a hole or match is tied, the pot carries over to the next hole or match.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },

  // ─── GROUP & FORMAT RULES ────────────────────────────────────────────────────
  {
    id: 'group_min_players',
    category: 'group',
    label: 'Minimum players',
    description: 'Minimum number of players required to run this game format.',
    valueType: 'number',
    valueConfig: { min: 2, max: 8, step: 1 },
    defaultValue: 2,
    implemented: false,
  },
  {
    id: 'group_pickup_rule',
    category: 'group',
    label: 'Pickup rule',
    description: 'Players may pick up (record max score) once they are out of contention on a hole.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'group_sub_in',
    category: 'group',
    label: 'Sub-in handicap adjustment',
    description: 'Adjust the handicap strokes for a substitute player entering mid-round.',
    valueType: 'number',
    valueConfig: { min: 0, max: 36, step: 1 },
    defaultValue: 0,
    implemented: false,
  },
  {
    id: 'group_teams_fixed',
    category: 'group',
    label: 'Fixed teams',
    description: 'Teams are set before the round and do not change.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'group_teams_rotating',
    category: 'group',
    label: 'Rotating teams',
    description: 'Team assignments rotate on a schedule (e.g., every six holes).',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
  {
    id: 'group_wolf_lone_multiplier',
    category: 'group',
    label: 'Wolf lone-wolf multiplier',
    description: 'When the Wolf goes it alone, winnings/losses are multiplied by this factor.',
    valueType: 'number',
    valueConfig: { min: 1, max: 4, step: 1 },
    defaultValue: 2,
    implemented: false,
  },
  {
    id: 'group_point_bank',
    category: 'group',
    label: 'Point bank',
    description: 'Track a shared point bank that players contribute to and draw from over multiple rounds.',
    valueType: 'none',
    defaultValue: null,
    implemented: false,
  },
];

// Lookup by id
export const PRIMITIVE_MAP: Record<string, HouseGamePrimitive> =
  Object.fromEntries(PRIMITIVES.map(p => [p.id, p]));

// Group by category for UI rendering
export const PRIMITIVES_BY_CATEGORY: Record<string, HouseGamePrimitive[]> =
  PRIMITIVES.reduce((acc, p) => {
    if (!acc[p.category]) acc[p.category] = [];
    acc[p.category].push(p);
    return acc;
  }, {} as Record<string, HouseGamePrimitive[]>);

export const CATEGORY_LABELS: Record<string, string> = {
  press: 'Press Rules',
  scoring: 'Scoring Structure',
  bonus: 'Multipliers & Bonuses',
  carryover: 'Carryover Rules',
  handicap: 'Handicap Application',
  casual: 'Gimmes & Casual Rules',
  settlement: 'Settlement',
  group: 'Group & Format Rules',
};

export const CATEGORY_ORDER = ['scoring', 'press', 'bonus', 'carryover', 'handicap', 'casual', 'settlement', 'group'];
